name: Go Build and Deploy

on:
  push:
    branches:
      - main # Set this to your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Git Pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/ubuntu/projects/golang-oracle && git pull && go build main.go

      - name: Restart Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo systemctl restart oracle.service
